### PR TITLE
Fix expenses report

### LINKED ISSUE #445: Error in expense.expenses with project selected on download from fb
If project is automatically selected for a result account on invoice when downloaded from fb, it does not show in expense.expenses. 
It is correctly calculated in report.regnskapsrapport.

### PR DESCRIPTION
**Pull request by mladjo2505**
Closes #445

### CODE REVIEW

File: modules/expense/view/expenses.php [hunk 1]
```diff
@@ -5,29 +5,36 @@
...
-  $cid = $_REQUEST['department_id'] ? $_REQUEST['department_id'] : 0;
+  $cid = $_REQUEST['department_id'] ? $_REQUEST['department_id'] : null;
   // All logic around this report was made to depend on year and department.
   // Since request is changed to have from - to period (important just for one part of report),
   // we will keep rest of report to have set year dependent on from date.
   $year = $_lib['date']->get_this_year($start_period);
 
-  $departmentQuery = "SELECT * FROM companydepartment WHERE CompanyDepartmentID=$cid";
-  $department = $_lib['db']->db_fetch_object($_lib['db']->db_query($departmentQuery));
+  if ($cid) {
```
Comment (mladjo2505) [inline modules/expense/view/expenses.php]: !is_null in the if

File: modules/expense/view/expenses.php [hunk 2]
```diff
@@ -5,29 +5,36 @@
...
   create_year($year, $_lib['db']);
 
   $yearQuery = "SELECT * FROM expense_periods WHERE year=$year";
   $yearObj = $_lib['db']->db_fetch_object($_lib['db']->db_query($yearQuery));
 
   create_defaults($yearObj->id, $cid, $_lib['db']);
-
-  $linesQuery = "SELECT * FROM expense_lines WHERE department_id=" . $cid . " AND expense_period_id=" . $yearObj->id;
+  $department_id_query_part = "";
+  if ($cid) {
```
Comment (mladjo2505) [inline modules/expense/view/expenses.php]: same as above

File: modules/expense/view/record.inc [hunk 3]
```diff
@@ -135,15 +135,22 @@
   # Create group and project reports if they don't exist
   # Executed on each request
   function create_defaults($period_id, $department_id, $db) {
-    $groups = $db->db_numrows($db->db_query("SELECT * FROM expense_groups WHERE department_id=$department_id AND expense_period_id=$period_id"));
+    $department_id_query_part = "";
+    if ($department_id) {
```
Comment (mladjo2505) [inline modules/expense/view/record.inc]: !is_null in if

**Review by sls-lnluksa — APPROVED** [review]

**Review by stoivo — APPROVED** [review]

**Review by stoivo — APPROVED** [review]
