### PR TITLE
Fix pagination on sale invoices page

### LINKED ISSUE #306: Sale invoices page is slow
Sale invoices page is slow because of line control is done for each invoice.

Find all 1+N queries and check if you can make it 1 or 2

- [x] Option one is to have one line control query for all invoices 
- [ ] Option two is to have a report page 
- [ ] Option tree is to load small batches of line control after the page is loaded.
- [x] Option four is to use pagination  

Fix pagination anyway

### PR DESCRIPTION
**Pull request by mladjo2505**
Closes #306

### CODE REVIEW

File: modules/invoice/view/listoutgoing.php [hunk 1]
```diff
@@ -181,24 +159,33 @@
...
         else
             {?> &gt;&gt; <?}
         ?>
     </th>
 </tr>
 <tr>
-    <th align="right">Faktura nr</th>
+    <th align="right">
+<? if ($sort == 'DESC') { ?>
+<a href="<? print $MY_SELF ?>&amp;page=<? print $page; ?>&amp;searchstring=<? print "$searchstring"; ?>&amp;InvoiceStatus=<? print "$InvoiceStatus"; ?>&amp;order_by=<? print "$order_by"; ?>&amp;sort=ASC" title="reverse sort">v</a>
```
Comment (mladjo2505) [inline modules/invoice/view/listoutgoing.php]: translate tooltip on final review

**Review by sls-lnluksa — APPROVED** [review]
All is ready for final review.

**Comment by sls-lnluksa** [comment]
First round review: Nikola Lukovic (sls-lnluksa)
Final review with: @stoivo

**Review by stoivo — APPROVED** [review]
